apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-rotta-gt-cert
  namespace: playground
spec:
  secretName: whoami-rotta-gt-cert-secret
  isCA: true
  commonName: '*.rotta.gt'
  dnsNames:
    - rotta.gt
    - '*.rotta.gt'
  issuerRef:
    name: rotta-ca-issuer
    kind: ClusterIssuer
