apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-ui-rotta-gt-cert
  namespace: container-registry
spec:
  secretName: registry-ui-rotta-gt-cert-secret
  isCA: true
  commonName: '*.rotta.gt'
  dnsNames:
    - rotta.gt
    - '*.rotta.gt'
  issuerRef:
    name: rotta-ca-issuer
    kind: ClusterIssuer
